# MySQL. Versions 5.0 and up are supported.
#
# Install the MySQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.7/en/old-client.html
#
default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: postgres
  password: root
  host: localhost
  port: 5432

development:
  <<: *default
  database: MDS_development
