default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: postgres
  password: root
  host: localhost
  port: 5432

development:
  <<: *default
  database: MDS_development

test:
   adapter: postgresql
   encoding: utf8
   pool: 5
   username: postgres
   password: root
   host: localhost
   port: 5432
   database: SeriesTracker_test

production:
 <<: *default
 database: SeriesTracker_production